@startuml
title FruitDash - Deployment View - Heartbeat Monitor

cloud "Front-end Server" as appcloud <<cloud>> {
 [Dashboard] as DASH
 [Data Extractor] as DE
 [Graph Extractor] as GE
}
cloud "Identity Server" as identitycloud <<cloud>> {
 [Identity Service] as IS
}

database "Analytical " as analyticaldb <<dbServer>>  {
 [Analytical Database] as ADB
}
database "Operational" as operationaldb <<dbServer>> {
 [Operational Database] as ODB
}

node "ETL" as transformer <<hostingServer>> {
    [Data Processor] as T
}
' node "Data API" as dataapi <<hostingServer>> {
'     [Data API] as API
' }
node "Watchdog" as watchdog1 <<hostingServer>> {
    [Watchdog1] as WTD1
}
node "Watchdog" as watchdog2 <<hostingServer>> {
    [Watchdog2] as WTD2
}

' Identity
' API -- IS: HTTPS
DASH -- IS: HTTPS

' Dashboard interactions
DASH -- DE
DASH -- GE
' DASH - API: HTTPS
DASH - ADB: HTTPS

' Data Transformer
ODB -- T: HTTP
T -- ADB: HTTP

' Data sourcing
API -- ADB: HTTP

' Watchdog
WTD1 -- T: HTTP 
WTD2 -- DASH: HTTP

@enduml